### ISSUE TITLE
Possible simplifications in build file

### ISSUE THREAD

**Issue by marcgrue** [vmunier/play-scalajs.g8#112]
This is firmly in the nice-to-have and I-could-probably-be-wrong department, but anyway, here we go:

I have found that I can omit enabling the ScalaJSPlugin in my Client projects:

    .enablePlugins(ScalaJSWeb) // seems enough
    // instead of:  .enablePlugins(ScalaJSPlugin, ScalaJSWeb)

And also I haven't needed to add this configuration in the shared cross project:

    .jsConfigure(_.enablePlugins(ScalaJSWeb))

In both cases, I understand that this could of course just be due to how I usually setup Play. But in case these two settings are actually not needed, it would be nice to simplify the g8 template.

**Comment by vmunier** [comment]
Hi!
* Enabling `ScalaJSWeb` is enough to make the build work, since it already includes `ScalaJSPlugin`. However, one may want to specify their own version of Scala.js and not depend on the Scala.js version included with sbt-web-scalajs.
* `.jsConfigure(_.enablePlugins(ScalaJSWeb))` is needed to configure sourcemaps on the shared project. Let's say you remove `.jsConfigure(_.enablePlugins(ScalaJSWeb))` and make the following modifications:
```
// SharedMessages.scala
object SharedMessages {
  def itWorks = "It works!"
  def exception = throw new Exception("Hey!")
}
```

```
// ScalaJSExample.scala
...
  def main(args: Array[String]): Unit = {
    dom.document.getElementById("scalajsShoutOut").textContent = SharedMessages.itWorks
    SharedMessages.exception
  }
```
then run the project:
```
$ sbt
sbt> <root>/clean
sbt> server/run
```
open `localhost:9000` in a browser (preferably in an incognito window to be sure the cache is empty). You can open the Web Console and hover `SharedMessages.scala:5`. It should display `file:///.../SharedMessages.scala:5`, i.e. it's using the `file://` protocol, which is fine when running the project locally as the file exists on your machine, but it will not work when deploying to a server where the file will not exist on that local path.
Conversely, when keeping `.jsConfigure(_.enablePlugins(ScalaJSWeb))`, the link should be `http://localhost:9000/versionedAssets/.../SharedMessages.scala:5`, i.e. fetching the Scala file from the Play server (Scala file that was packaged by `ScalaJSWeb`). This method works both locally and on a remote server.

**Comment by marcgrue** [comment]
Thanks for the thorough explanation and amendments! It all makes sense to me now.
